version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: one_blog_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=one_blog
